### ISSUE TITLE
（リンクに帰る部分）ってURLを置く場所って事じゃないの？

### ISSUE THREAD

**Issue by yutanisida** [nanoFreaks/yobimori_terms_of_service#5]
https://github.com/nanoFreaks/yobimori_terms_of_service/blob/3e8fce2197af99268529be043ef27ebf473712e5/index.html#L40

**Comment by ssssota** [comment]
たしかにおかしい

**Comment by ssssota** [comment]
`<a href="/yobimori_privacy_policy/">プライバシーポリシー</a>`とかになる？
